---
title: "numeric_eda"
output: "github_document"
date: "2022-10-06"
---

```{r}
library(tidyverse)
library(lubridate)
```

# Code from the class site
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
select(name, id, everything())
weather_df
```


## group_by()
```{r}
weather_df %>% 
  group_by(name, month)
```

## Summarzied 
```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    n_obs = n()
  )
```

## count in the other ways?
```{r}
weather_df %>% 
  count(name, month)
```

#Don't use "table()"
```{r}
weather_df %>% 
  pull(month) %>% 
  table()
```

# you can have multiple summaries
```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    n_obs= n(),
    n_dist= n_distinct(date)
  )
```

# a brief aside on 2*2 tables
```{r}
weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  group_by(name, cold) %>% 
  summarize(n_obs= n()) %>% 
  pivot_wider(
    names_from = cold,
    values_from = n_obs
  )
```

```{r}
weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ "THIS IS S PROBLEM"
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  janitor::tabyl(name,cold)
```


#General summaries
```{r}
weather_df %>%
  group_by(name,month) %>%
  summarize(
    n_obs= n(),
    mean_tmax = mean(tmax, na.rm = TRUE),
    sd_prcp = sd(prcp),
    median_tmax = median(tmax))
    
```


```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarise(across(prcp:tmin, mean))
```

# this is a dataframe!!
```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>%
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
    geom_point() + geom_line() + 
    theme(legend.position = "bottom")
```


```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax) %>% 
  knitr::kable(digits = 1)
```

#Grouped mutates
```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) +
  geom_point()
```

#lagged observations
```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(yestaerday_tmax = lag(tmax),
         tmax_change = tmax - yestaerday_tmax) %>% 
  summarise(sd_chaneg = sd(tmax_change, na.rm = TRUE))
```

# One other window function
```{r}
weather_df %>%
  group_by(name, month) %>%
  mutate(tmax_rank = min_rank(tmax)) %>% 
  filter(tmax_rank < 4) %>% 
  arrange(name, month, tmax_rank)
```

