---
title: "viz_and_eda"
output: github_document
date: "2022-09-29"
---
# Let's Import data
```{r setup, include = FALSE}
library(tidyverse)
library(ggridges)
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

#Let's make scaterplot
```{r}
ggplot(weather_df, aes(x = tmin, y= tmax))+ geom_point()
```

# Let's make the same scaterplot , but different
```{r}
weather_df %>% 
  drop_na() %>% 
  filter(name== "CentralPark_NY") %>% 
  ggplot(aes(x = tmin, y= tmax))+ geom_point()
```

#make plot but differernt
```{r}
weather_scatterplot=
  weather_df %>% 
  drop_na() %>% 
  ggplot(aes(x = tmin, y= tmax))

weather_scatterplot+ geom_point()
```


## Make plot fancy
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y= tmax, color = name)) + geom_point()
```


```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y= tmax,color = name)) + 
  geom_point()+ 
  geom_smooth()
```
# alpha is make points tranparent
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y= tmax,color = name)) + 
  geom_point(alpha = .3)+ 
  geom_smooth(se = FALSE)
```

#mAKE sepaerate panels: facet_grid(xx~xx)
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y= tmax,color = name)) + 
  geom_point(alpha = .3) + 
  geom_smooth(se = FALSE) +
  facet_grid(.~name)
```


# tmax vs tmin boring, spice it up some, se= define confident interval around the line
```{r}
weather_df %>% 
  ggplot(aes(x=date, y=tmax, color = name))+
  geom_point(aes(size = prcp, alpha = .3))+
  geom_smooth(se=FALSE)+
  facet_grid(.~name)
```

## quick stuff
```{r}
weather_df %>% 
  ggplot(aes(x=date, y=tmax))+
  geom_hex()
```

```{r}
weather_df %>% 
  ggplot(aes(x=tmax, fill= name))+
  geom_histogram()+
  facet_grid()
```


# more option
```{r}
weather_df %>% 
  ggplot(aes(x=tmax, fill = name))+
  geom_density(alpha = .3)
```

```{r}
weather_df %>% 
  ggplot(aes(x= name, y = tmax, fill =name))+
  geom_boxplot()
```


```{r}
weather_df %>% 
  ggplot(aes(x= name, y = tmax, fill =name))+
  geom_violin()
```

```{r}
weather_df %>% 
  ggplot(aes(x= tmax, y = name))+
  geom_density_ridges()
```

# save the plot

```{r}
weather_scatterplot =
  weather_df %>% 
  ggplot(aes(x= date, y = tmax, color =name))+
  geom_point(aes(size= prcp), alpha =.3)+
  geom_smooth(se= FALSE)+
  facet_grid(.~name)

weather_scatterplot

ggsave(
  file = "results/weather_scatterplot.pdf",
  plot = weather_scatterplot,
  width = 8, height = 5)
```

```{r,fig.width=10}
weather_scatterplot
```

